export let ANIMATIONS = {
  DEATH: "Death",
  DEFEND: "Defend",
  GROUNDKICK: "GroundKick",
  GROUNDPUNCH: "GroundPunch",
  HIT1: "Hit1",
  HIT2: "Hit2",
  IDLE: "Idle",
  JUMP: "Jump",
  JUMPKICK: "JumpKick",
  KICK1: "Kick1",
  KICK2: "Kick2",
  KNOCKDOWN: "KnockDown",
  LAND: "Land",
  PICKUP: "Pickup",
  PUNCHCOMBO: "PunchCombo",
  PUNCHROOTMOTION: "PunchRootMotion",
  RUN: "Run",
  STANDUP: "StandUp",
  SWINGWEAPON: "SwingWeapon",
  THROWWEAPON: "ThrowWeapon",
  WALK: "Walk",
};
